Intake mech
Tino-FRC-2473/FRC2022-SummerTraining pull request #23
Opened 2022-08-02 00:17 UTC by adnx26

2022-08-10 06:01 UTC, AG6GR requested changes

2022-08-10 06:01 UTC, AG6GR commented on src/main/java/frc/robot/systems/monkeFSM.java
> +	private void handleFirstRetractState(TeleopInput input) {
You should also set the solenoid in every state handler as well, to make it clear what the intended position is.

2022-08-10 06:01 UTC, AG6GR commented on .gitignore
> +.idea/workspace.xml
Just add one entry for `.idea` to ignore the entire folder.

2022-08-11 20:47 UTC, andrewqin29 commented on src/main/java/frc/robot/systems/monkeFSM.java
> +	private FSMState nextState(TeleopInput input) {
diagram committed to repo

2022-08-11 20:52 UTC, andrewqin29 commented on src/main/java/frc/robot/systems/monkeFSM.java
> +	private DigitalInput armLimitSwitchFirst;
we thought we would need one for fully retracted, the little extension, as well as the extension to swing onto the next bar (handleArmPistonExtendState) for a combined total of 3. we haven't had a thorough discussion with hardware team regarding limit switches yet.

2022-08-11 20:55 UTC, andrewqin29 commented on src/main/java/frc/robot/systems/monkeFSM.java
> +	private DigitalInput armLimitSwitchFirst;
also, wasn't really sure how to declare the limit switches from the documentation provided. I committed and pushed my best guess onto the repo so could you check that. the only cansparkmax we declared was armMotor so I just did armMotor.getForwardLimitSwitch() for all three limitswitches. but I'm confused on why the armMotor would be responsible for connecting to the limitswitches in the first place.

2022-08-23 01:18 UTC, AG6GR approved these changes

2022-08-23 01:44 UTC, merged